[tools]
argocd = "3.3.6"
aws = { version = "2.36.40", symlink_bins = "true" }
bun = "1.4.0"
delta = "0.19.2"
dyff = "1.12.0"
elixir = "1.19.3-otp-28"
erlang = "28.1.1"
"github:can1357/oh-my-pi" = "18.1.16"
"github:henriklovhaug/md-tui" = "0.10.3"
"github:nklmilojevic/sofka" = "v0.24.8"
"github:openeverest/openeverest" = "1.15.2"
"github:plantuml/plantuml" = "latest"
"github:radiusmethod/awsd" = "latest"
"github:rtk-ai/rtk" = "dev-0.49.0-rc.418"
"github:szhekpisov/diffyml" = "v1.6.2"
gleam = "1.13.0"
go = "1.24.2"
"go:github.com/steveyegge/beads/cmd/bd" = "0.42.0"
helm = "latest"
herdr = "0.9.0"
k3d = "5.8.3"
k9s = "0.51.0"
kompose = "latest"
kubectl = "1.31.5"
kubectx = "latest"
kubeseal = "0.36.6"
kustomize = "latest"
lazydocker = "latest"
lazygit = "0.65.0"
neovim = "0.12.5"
node = "latest"
"npm:@postgres-language-server/cli" = "latest"
"npm:calldiff" = "latest"
"npm:pake-cli" = "3.7.8"
rust = "latest"
terraform = "1.12.1"
terragrunt = "0.81.0"
uv = "latest"
vault = "2.0.1"
worktrunk = "0.66.0"
zig = "0.15.2"

[settings]
experimental = true

[settings.npm]
bun = true
