- name: Set Up
  hosts: local
  become: true
  vars:
    - NODE_VERSION: "16"
    - FLUTTER_VERSION: "3.3.4"
    - LAZYGIT_VERSION: "0.40.2"
    - GCM_VERSION: "2.3.0"
  roles:
    - role: zsh
      tags:
        - zsh
    - {
        role: diodonfrost.p10k,
        p10k_prompt_style: "rainbow",
        zsh_plugin: ohmyzsh,
        p10k_transient_prompt: "yes",
        tags: p10k,
      }
    - role: nvim
      tags:
        - nvim
    - role: node
      tags:
        - node
    - role: rust
      tags:
        - rust
    - {
        role: geerlingguy.docker,
        docker_users: ["{{ user }}"],
        tags: docker,
        become: true,
        become_method: sudo,
      }
    - role: terraform
      tags:
        - terraform
    - role: tmux
      tags:
        - tmux
